name: Publish Snapshot
run-name: Publish Snapshot

concurrency:
  group: snapshot

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draft new release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run tests
        run: xvfb-run ./gradlew test

      - name: Publish to Snapshots Repository
        uses: gradle/actions/setup-gradle@v3
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
        with:
          dependency-graph: generate-and-submit
          artifact-retention-days: 1
          arguments: publishToMavenCentral
